#pragma once

#include <cstddef>
#include <cstdint>
#include <deque>
#include <memory>
#include <optional>
#include <unordered_map>
#include <vector>

#include <fire_engine/collision/aabb.hpp>
#include <fire_engine/collision/broad_phase.hpp>
#include <fire_engine/collision/dynamic_aabb_tree_broad_phase.hpp>
#include <fire_engine/collision/narrow_phase.hpp>
#include <fire_engine/graphics/cloth.hpp>
#include <fire_engine/physics/collider_shape.hpp>
#include <fire_engine/physics/contact.hpp>
#include <fire_engine/physics/contact_solver.hpp>
#include <fire_engine/physics/island.hpp>
#include <fire_engine/physics/joint.hpp>
#include <fire_engine/physics/joint_solver.hpp>
#include <fire_engine/physics/physics_body.hpp>
#include <fire_engine/physics/physics_handle.hpp>
#include <fire_engine/scene/transform.hpp>

namespace fire_engine
{

class PhysicsWorld
{
public:
    PhysicsWorld() = default;

    // Inject a broadphase implementation (testing / alternative strategies). The
    // default ctor uses a DynamicAabbTreeBroadPhase; this lets a caller substitute, say,
    // a SweepAndPruneBroadPhase without changing any call site.
    explicit PhysicsWorld(std::unique_ptr<BroadPhase> broadPhase)
        : broadPhase_{std::move(broadPhase)}
    {
    }

    ~PhysicsWorld() = default;

    PhysicsWorld(const PhysicsWorld&) = delete;
    PhysicsWorld& operator=(const PhysicsWorld&) = delete;
    PhysicsWorld(PhysicsWorld&&) noexcept = default;
    PhysicsWorld& operator=(PhysicsWorld&&) noexcept = default;

    [[nodiscard]]
    PhysicsBodyHandle createBody(const PhysicsBodyDesc& desc);

    [[nodiscard]]
    PhysicsColliderHandle createCollider(PhysicsBodyHandle bodyHandle, const ColliderDesc& desc);

    // Create a compound collider: one child collider per CompoundChild (each placed at
    // its local offset and registered with the broadphase). For a Dynamic body the
    // children's mass properties are aggregated into the body's centre of mass +
    // inertia (mass split by child volume; parallel-axis sum, diagonalised). Returns
    // the first child's handle (or a null handle if `children` is empty / body invalid).
    [[nodiscard]]
    PhysicsColliderHandle
    createCompoundCollider(PhysicsBodyHandle bodyHandle, const std::vector<CompoundChild>& children,
                           std::uint32_t collisionLayer = 1U, std::uint32_t collisionMask = ~0U);

    // Create a static triangle-mesh collider. A moving body is resolved against the
    // mesh's actual triangles (via a per-collider triangle BVH), not its bounding box.
    // The body must be Static (returns a null handle otherwise) and is assumed to keep
    // a fixed transform (the triangle BVH is built once in world space).
    [[nodiscard]]
    PhysicsColliderHandle
    createMeshCollider(PhysicsBodyHandle bodyHandle, const StaticMeshShape& mesh,
                       const PhysicsMaterial& material = {}, std::uint32_t collisionLayer = 1U,
                       std::uint32_t collisionMask = ~0U);

    [[nodiscard]]
    bool destroyBody(PhysicsBodyHandle handle);

    // Create a constraint (distance / ball-socket / hinge) between two bodies. The
    // descriptor's anchors/axes are in each body's local frame; both bodies must be
    // valid. Returns a null handle if either body is missing.
    [[nodiscard]]
    PhysicsConstraintHandle createJoint(const JointDesc& desc);

    [[nodiscard]]
    bool destroyJoint(PhysicsConstraintHandle handle);

    void clear();
    void step(float fixedDt);

    [[nodiscard]]
    bool valid(PhysicsBodyHandle handle) const noexcept;

    [[nodiscard]]
    bool valid(PhysicsColliderHandle handle) const noexcept;

    [[nodiscard]]
    bool valid(PhysicsConstraintHandle handle) const noexcept;

    [[nodiscard]]
    std::size_t bodyCount() const noexcept;

    [[nodiscard]]
    std::size_t colliderCount() const noexcept;

    [[nodiscard]]
    std::size_t jointCount() const noexcept;

    // World-space collision primitives for the cloth/soft-body solver — each
    // active collider's shape composed with its body transform. Vulkan-free
    // output (mirrors the gatherLights / gatherEmitters pattern).
    [[nodiscard]]
    std::vector<ClothCollider> gatherColliders() const;

    // --- Debug visualisation (read-only, Vulkan-free) ---
    //
    // World-space AABBs of every active collider (broadphase bounds), and the
    // contacts generated by the most recent step() (approximate point + normal).
    // The renderer's debug-draw subsystem consumes these; gatherColliders()
    // supplies the authored collider shapes.
    [[nodiscard]]
    std::vector<AABB> debugColliderBounds() const;

    [[nodiscard]]
    const std::vector<DebugContact>& debugContacts() const noexcept
    {
        return debugContacts_;
    }

    [[nodiscard]]
    const PhysicsBody* body(PhysicsBodyHandle handle) const noexcept;

    [[nodiscard]]
    PhysicsBody* body(PhysicsBodyHandle handle) noexcept;

    [[nodiscard]]
    std::optional<Transform> bodyTransform(PhysicsBodyHandle handle) const noexcept;

    void setBodyTransform(PhysicsBodyHandle handle, const Transform& transform) noexcept;
    void setBodyVelocity(PhysicsBodyHandle handle, Vec3 velocity) noexcept;

    // Wake a sleeping body (and reset its sleep timer). A no-op for a body that is
    // already awake or invalid. Mutating a body's velocity/transform wakes it too.
    void wake(PhysicsBodyHandle handle) noexcept;

    // Whether a body is currently asleep (skipped by the solver until disturbed).
    [[nodiscard]]
    bool sleeping(PhysicsBodyHandle handle) const noexcept;

    // Global on/off for the sleeping system (default on). Disabling wakes nothing
    // already asleep but stops new islands from sleeping.
    void sleepingEnabled(bool enabled) noexcept
    {
        sleepingEnabled_ = enabled;
    }

    [[nodiscard]]
    bool sleepingEnabled() const noexcept
    {
        return sleepingEnabled_;
    }

    [[nodiscard]]
    const std::vector<CollisionPair>& possiblePairs() const noexcept
    {
        return broadPhase_->possiblePairs();
    }

    [[nodiscard]]
    bool validateBroadPhase() const
    {
        return broadPhase_->validate();
    }

private:
    struct BodyEntry
    {
        PhysicsBodyHandle handle;
        PhysicsBody body;
        Transform transform;
        Vec3 previousPosition{};
        bool active{true};
        std::vector<PhysicsColliderHandle> colliders;
        // Sleeping (P5): `sleeping` skips this body from integration + solving; the
        // timer accumulates while the body is below the sleep thresholds and resets
        // when it moves or is woken. Driven per-island in solveAndIntegrate.
        bool sleeping{false};
        float sleepTimer{0.0f};
    };

    // Per-collider triangle-mesh data (static mesh colliders only): the triangles in
    // world space + a BVH over them. Built once at createMeshCollider (the mesh body is
    // assumed not to move). Shared so ColliderEntry stays copyable.
    struct MeshCollisionData
    {
        std::vector<Vec3> worldVertices;
        std::vector<std::uint32_t> indices;
        AabbBvh<int> bvh{0.0f}; // triangle index → world AABB
    };

    struct ColliderEntry
    {
        PhysicsColliderHandle handle;
        PhysicsBodyHandle body;
        Collider collider;
        ColliderShape shape;
        PhysicsMaterial material;
        // Offset of this collider within the body (a compound child); identity for a
        // plain single collider. worldShape composes it after the body transform.
        Vec3 localPosition{};
        Quaternion localRotation{Quaternion::identity()};
        bool active{true};
        // Non-null for a static triangle-mesh collider; null otherwise.
        std::shared_ptr<MeshCollisionData> mesh;
    };

    struct JointEntry
    {
        PhysicsConstraintHandle handle;
        JointDesc desc;
        // Relative orientation of B in A's frame at creation time — the rest frame
        // the angular limits are measured from.
        Quaternion restRelative{};
        bool active{true};
    };

    struct ContactCandidate
    {
        BodyEntry* moving{nullptr};
        BodyEntry* target{nullptr};
        ColliderEntry* movingCollider{nullptr};
        ColliderEntry* targetCollider{nullptr};
    };

    struct SolverContact
    {
        ContactManifold manifold; // normal points target -> moving; push moving out
        BodyEntry* moving{nullptr};
        BodyEntry* target{nullptr};
        ColliderEntry* movingCollider{nullptr};
        ColliderEntry* targetCollider{nullptr};
        // Distinguishes several contacts from one collider pair (a mesh triangle index
        // + 1); 0 for an ordinary single-manifold pair. Folded into the warm-start key.
        std::uint32_t subKey{0};
    };

    PhysicsBodyHandle nextBodyHandle_{PhysicsBodyHandle{1U}};
    PhysicsColliderHandle nextColliderHandle_{PhysicsColliderHandle{1U}};
    PhysicsConstraintHandle nextJointHandle_{PhysicsConstraintHandle{1U}};
    std::vector<BodyEntry> bodies_;
    std::deque<ColliderEntry> colliders_;
    std::vector<JointEntry> joints_;
    // Side-tables for O(1) lookup into the entry containers, keyed by handle
    // value and (for the broadphase's pair pointers) by Collider address.
    // Entries are tombstoned, never erased before clear(), so the stored indices
    // stay valid for the container's lifetime; find* still checks `active`.
    std::unordered_map<std::uint32_t, std::size_t> bodyIndexByHandle_;
    std::unordered_map<std::uint32_t, std::size_t> colliderIndexByHandle_;
    std::unordered_map<std::uint32_t, std::size_t> jointIndexByHandle_;
    std::unordered_map<const Collider*, std::size_t> colliderIndexByPointer_;
    // Owned via the BroadPhase interface so the implementation is swappable. Defaults to
    // the dynamic AABB tree; inject an alternative (e.g. SweepAndPruneBroadPhase) through
    // the unique_ptr constructor.
    std::unique_ptr<BroadPhase> broadPhase_{std::make_unique<DynamicAabbTreeBroadPhase>()};
    NarrowPhase narrowPhase_;
    ContactSolver solver_;
    JointSolver jointSolver_;
    Vec3 gravity_{0.0f, -9.81f, 0.0f};
    bool sleepingEnabled_{true};
    // Contacts from the most recent step(), kept for debug visualisation only.
    std::vector<DebugContact> debugContacts_;

    // Create a Collider + ColliderEntry for `shape` at a local offset within `owner`,
    // register it with the broadphase, and return its handle. Shared by createCollider
    // (identity offset) and createCompoundCollider (per-child offsets). Does not touch
    // the body's mass properties — the caller aggregates those.
    [[nodiscard]]
    PhysicsColliderHandle
    addColliderEntry(BodyEntry& owner, const ColliderShape& shape, const PhysicsMaterial& material,
                     std::uint32_t collisionLayer, std::uint32_t collisionMask,
                     const Vec3& localPosition, const Quaternion& localRotation);

    [[nodiscard]]
    BodyEntry* findBody(PhysicsBodyHandle handle) noexcept;

    [[nodiscard]]
    const BodyEntry* findBody(PhysicsBodyHandle handle) const noexcept;

    [[nodiscard]]
    ColliderEntry* findCollider(PhysicsColliderHandle handle) noexcept;

    [[nodiscard]]
    const ColliderEntry* findCollider(PhysicsColliderHandle handle) const noexcept;

    [[nodiscard]]
    ColliderEntry* findCollider(const Collider* collider) noexcept;

    // Compose each active joint's local anchors/axes with the current body
    // transforms into the world-space JointInputs the solver consumes (skipping any
    // joint whose bodies are no longer valid). `bodyIndex` maps a body handle to its
    // solver-body index.
    [[nodiscard]]
    std::vector<JointInput> buildJointInputs() const;

    [[nodiscard]]
    AABB localBounds(const ColliderShape& shape) const noexcept;

    // Compose a collider's authored shape with its body's world transform into a
    // neutral world-space shape for the narrowphase (and gatherColliders).
    [[nodiscard]]
    WorldShape worldShape(const ColliderEntry& entry) const;

    void updateCollider(ColliderEntry& collider, float dt);
    void resetCollider(ColliderEntry& collider);
    void updateColliders(float dt);
    void resetResolvedColliders();
    void capturePreviousPositions() noexcept;

    [[nodiscard]]
    std::vector<SolverContact> contacts(float dt);

    // Rebuild debugContacts_ from this step's solver contacts (real manifold
    // points + normal), before the solver mutates positions.
    void captureDebugContacts(const std::vector<SolverContact>& contacts);

    // Append the solver contact(s) for one broadphase pair to `out`: a single manifold
    // for a primitive/convex pair, or one per overlapping triangle for a static-mesh
    // pair (mesh as the target). Nothing when there's no contact.
    void appendContactsForPair(const CollisionPair& pair, float dt,
                               std::vector<SolverContact>& out);

    [[nodiscard]]
    std::optional<SolverContact> singleContact(const ContactCandidate& candidate, float dt);

    void appendMeshContacts(const ContactCandidate& candidate, float dt,
                            std::vector<SolverContact>& out);

    [[nodiscard]]
    std::optional<ContactCandidate> contactCandidateForPair(const CollisionPair& pair);

    // Integrate constrained velocities + positions for this step: build the global
    // SolverBody view + contact/joint inputs from the frame's contacts, partition the
    // dynamic bodies into islands, solve + integrate each island independently, then
    // write the results back onto the bodies. Returns true if any body moved.
    bool solveAndIntegrate(const std::vector<SolverContact>& contacts, float dt);

    // Solve one island: run the contact + joint solvers over the island's input
    // subset (indexing the shared `solverBodies` array), then integrate the island's
    // dynamic bodies' velocities into positions/orientations and position-correct.
    void solveIsland(const Island& island, std::vector<SolverBody>& solverBodies,
                     const std::vector<SolverContactInput>& contactInputs,
                     const std::vector<JointInput>& jointInputs, float dt);

    // Whether the whole island may sleep this step: sleeping enabled, every dynamic
    // member allows sleeping and has been below the thresholds for kSleepTime, and no
    // kinematic member moved (a moving platform keeps its riders awake). An already-
    // asleep island stays asleep because its members keep their elapsed timers.
    [[nodiscard]]
    bool islandShouldSleep(const Island& island) const;

    [[nodiscard]]
    static bool movable(const BodyEntry& body) noexcept;

    // Velocity-pass inverse mass: the body's inverse mass for Dynamic, 0 for
    // Static/Kinematic (contact impulses never shove a scene-driven body).
    [[nodiscard]]
    static float velocityInvMass(const BodyEntry& body) noexcept;

    // Split-impulse positional-correction weight: 0 for static (immovable), the
    // inverse mass for dynamic, a nominal 1 for kinematic (so it slides out of
    // penetration).
    [[nodiscard]]
    static float positionWeight(const BodyEntry& body) noexcept;
};

} // namespace fire_engine
