#pragma once

#include <cstddef>
#include <cstdint>
#include <deque>
#include <optional>
#include <unordered_map>
#include <vector>

#include <fire_engine/collision/aabb.hpp>
#include <fire_engine/collision/narrow_phase.hpp>
#include <fire_engine/collision/sweep_and_prune_broad_phase.hpp>
#include <fire_engine/graphics/cloth.hpp>
#include <fire_engine/physics/collider_shape.hpp>
#include <fire_engine/physics/contact.hpp>
#include <fire_engine/physics/contact_solver.hpp>
#include <fire_engine/physics/joint.hpp>
#include <fire_engine/physics/joint_solver.hpp>
#include <fire_engine/physics/physics_body.hpp>
#include <fire_engine/physics/physics_handle.hpp>
#include <fire_engine/scene/transform.hpp>

namespace fire_engine
{

class PhysicsWorld
{
public:
    PhysicsWorld() = default;
    ~PhysicsWorld() = default;

    PhysicsWorld(const PhysicsWorld&) = delete;
    PhysicsWorld& operator=(const PhysicsWorld&) = delete;
    PhysicsWorld(PhysicsWorld&&) noexcept = default;
    PhysicsWorld& operator=(PhysicsWorld&&) noexcept = default;

    [[nodiscard]]
    PhysicsBodyHandle createBody(const PhysicsBodyDesc& desc);

    [[nodiscard]]
    PhysicsColliderHandle createCollider(PhysicsBodyHandle bodyHandle, const ColliderDesc& desc);

    [[nodiscard]]
    bool destroyBody(PhysicsBodyHandle handle);

    // Create a constraint (distance / ball-socket / hinge) between two bodies. The
    // descriptor's anchors/axes are in each body's local frame; both bodies must be
    // valid. Returns a null handle if either body is missing.
    [[nodiscard]]
    PhysicsConstraintHandle createJoint(const JointDesc& desc);

    [[nodiscard]]
    bool destroyJoint(PhysicsConstraintHandle handle);

    void clear();
    void step(float fixedDt);

    [[nodiscard]]
    bool valid(PhysicsBodyHandle handle) const noexcept;

    [[nodiscard]]
    bool valid(PhysicsColliderHandle handle) const noexcept;

    [[nodiscard]]
    bool valid(PhysicsConstraintHandle handle) const noexcept;

    [[nodiscard]]
    std::size_t bodyCount() const noexcept;

    [[nodiscard]]
    std::size_t colliderCount() const noexcept;

    [[nodiscard]]
    std::size_t jointCount() const noexcept;

    // World-space collision primitives for the cloth/soft-body solver — each
    // active collider's shape composed with its body transform. Vulkan-free
    // output (mirrors the gatherLights / gatherEmitters pattern).
    [[nodiscard]]
    std::vector<ClothCollider> gatherColliders() const;

    // --- Debug visualisation (read-only, Vulkan-free) ---
    //
    // World-space AABBs of every active collider (broadphase bounds), and the
    // contacts generated by the most recent step() (approximate point + normal).
    // The renderer's debug-draw subsystem consumes these; gatherColliders()
    // supplies the authored collider shapes.
    [[nodiscard]]
    std::vector<AABB> debugColliderBounds() const;

    [[nodiscard]]
    const std::vector<DebugContact>& debugContacts() const noexcept
    {
        return debugContacts_;
    }

    [[nodiscard]]
    const PhysicsBody* body(PhysicsBodyHandle handle) const noexcept;

    [[nodiscard]]
    PhysicsBody* body(PhysicsBodyHandle handle) noexcept;

    [[nodiscard]]
    std::optional<Transform> bodyTransform(PhysicsBodyHandle handle) const noexcept;

    void setBodyTransform(PhysicsBodyHandle handle, const Transform& transform) noexcept;
    void setBodyVelocity(PhysicsBodyHandle handle, Vec3 velocity) noexcept;

    [[nodiscard]]
    const std::vector<CollisionPair>& possiblePairs() const noexcept
    {
        return broadPhase_.possiblePairs();
    }

    [[nodiscard]]
    bool validateBroadPhase() const
    {
        return broadPhase_.validate();
    }

private:
    struct BodyEntry
    {
        PhysicsBodyHandle handle;
        PhysicsBody body;
        Transform transform;
        Vec3 previousPosition{};
        bool active{true};
        std::vector<PhysicsColliderHandle> colliders;
    };

    struct ColliderEntry
    {
        PhysicsColliderHandle handle;
        PhysicsBodyHandle body;
        Collider collider;
        ColliderShape shape;
        PhysicsMaterial material;
        bool active{true};
    };

    struct JointEntry
    {
        PhysicsConstraintHandle handle;
        JointDesc desc;
        // Relative orientation of B in A's frame at creation time — the rest frame
        // the angular limits are measured from.
        Quaternion restRelative{};
        bool active{true};
    };

    struct ContactCandidate
    {
        BodyEntry* moving{nullptr};
        BodyEntry* target{nullptr};
        ColliderEntry* movingCollider{nullptr};
        ColliderEntry* targetCollider{nullptr};
    };

    struct SolverContact
    {
        ContactManifold manifold; // normal points target -> moving; push moving out
        BodyEntry* moving{nullptr};
        BodyEntry* target{nullptr};
        ColliderEntry* movingCollider{nullptr};
        ColliderEntry* targetCollider{nullptr};
    };

    PhysicsBodyHandle nextBodyHandle_{PhysicsBodyHandle{1U}};
    PhysicsColliderHandle nextColliderHandle_{PhysicsColliderHandle{1U}};
    PhysicsConstraintHandle nextJointHandle_{PhysicsConstraintHandle{1U}};
    std::vector<BodyEntry> bodies_;
    std::deque<ColliderEntry> colliders_;
    std::vector<JointEntry> joints_;
    // Side-tables for O(1) lookup into the entry containers, keyed by handle
    // value and (for the broadphase's pair pointers) by Collider address.
    // Entries are tombstoned, never erased before clear(), so the stored indices
    // stay valid for the container's lifetime; find* still checks `active`.
    std::unordered_map<std::uint32_t, std::size_t> bodyIndexByHandle_;
    std::unordered_map<std::uint32_t, std::size_t> colliderIndexByHandle_;
    std::unordered_map<std::uint32_t, std::size_t> jointIndexByHandle_;
    std::unordered_map<const Collider*, std::size_t> colliderIndexByPointer_;
    SweepAndPruneBroadPhase broadPhase_;
    NarrowPhase narrowPhase_;
    ContactSolver solver_;
    JointSolver jointSolver_;
    Vec3 gravity_{0.0f, -9.81f, 0.0f};
    // Contacts from the most recent step(), kept for debug visualisation only.
    std::vector<DebugContact> debugContacts_;

    [[nodiscard]]
    BodyEntry* findBody(PhysicsBodyHandle handle) noexcept;

    [[nodiscard]]
    const BodyEntry* findBody(PhysicsBodyHandle handle) const noexcept;

    [[nodiscard]]
    ColliderEntry* findCollider(PhysicsColliderHandle handle) noexcept;

    [[nodiscard]]
    const ColliderEntry* findCollider(PhysicsColliderHandle handle) const noexcept;

    [[nodiscard]]
    ColliderEntry* findCollider(const Collider* collider) noexcept;

    // Compose each active joint's local anchors/axes with the current body
    // transforms into the world-space JointInputs the solver consumes (skipping any
    // joint whose bodies are no longer valid). `bodyIndex` maps a body handle to its
    // solver-body index.
    [[nodiscard]]
    std::vector<JointInput> buildJointInputs() const;

    [[nodiscard]]
    AABB localBounds(const ColliderShape& shape) const noexcept;

    // Compose a collider's authored shape with its body's world transform into a
    // neutral world-space shape for the narrowphase (and gatherColliders).
    [[nodiscard]]
    WorldShape worldShape(const ColliderEntry& entry) const;

    void updateCollider(ColliderEntry& collider, float dt);
    void resetCollider(ColliderEntry& collider);
    void updateColliders(float dt);
    void resetResolvedColliders();
    void capturePreviousPositions() noexcept;

    [[nodiscard]]
    std::vector<SolverContact> contacts(float dt);

    // Rebuild debugContacts_ from this step's solver contacts (real manifold
    // points + normal), before the solver mutates positions.
    void captureDebugContacts(const std::vector<SolverContact>& contacts);

    [[nodiscard]]
    std::optional<SolverContact> contactForPair(const CollisionPair& pair, float dt);

    [[nodiscard]]
    std::optional<ContactCandidate> contactCandidateForPair(const CollisionPair& pair);

    // Integrate constrained velocities + positions for this step: build the solver
    // views from the frame's contacts, run the sequential-impulse velocity solve,
    // integrate positions, then the split-impulse penetration correction, writing
    // the results back onto the bodies. Returns true if any body moved.
    bool solveAndIntegrate(const std::vector<SolverContact>& contacts, float dt);

    [[nodiscard]]
    static bool movable(const BodyEntry& body) noexcept;

    // Velocity-pass inverse mass: the body's inverse mass for Dynamic, 0 for
    // Static/Kinematic (contact impulses never shove a scene-driven body).
    [[nodiscard]]
    static float velocityInvMass(const BodyEntry& body) noexcept;

    // Split-impulse positional-correction weight: 0 for static (immovable), the
    // inverse mass for dynamic, a nominal 1 for kinematic (so it slides out of
    // penetration).
    [[nodiscard]]
    static float positionWeight(const BodyEntry& body) noexcept;
};

} // namespace fire_engine
