"""Shared builders for the repository's generated glTF assets.

The engine's owned scenes (the physics demos, and the shadow-LOD acceptance scene) are
generated rather than hand-authored, so their authored numbers stay readable and a
regenerated file is reproducible byte-for-byte. This package is the machinery those
generators share: geometry primitives, quaternion helpers, and the `Scene` assembler
that emits one self-contained `.gltf` with an embedded base64 buffer.

A generator script is expected to own only its scene content — what the boxes are, where
the lights point — and to import everything mechanical from here. Import it by putting
the repository's `tools/` directory on `sys.path` (see
`assets/physics_demos/generate.py`), which works regardless of the working directory the
script is run from.

Anything added here must keep existing generated assets byte-identical; they are
regenerated by the build (`physics_demos` target), so a formatting or ordering change
would show up as churn across every committed `.gltf`.
"""

from .geometry import (
    box_geometry,
    check_winding,
    combine_geometry,
    cylinder_geometry,
    mesh_from_triangles,
    normalise,
    quad_geometry,
    sphere_geometry,
    spiky_sphere_geometry,
    subdivided_box_geometry,
    tetrahedron_geometry,
    vec_cross,
    vec_sub,
)
from .png import checker_cutout_png, write_rgba_png
from .quaternions import (
    look_at_quat,
    quat_axis_angle,
    quat_conjugate,
    quat_from_to,
    quat_multiply,
    rotate_by_quat,
)
from .scene import Scene, write_gltf

__all__ = [
    "Scene",
    "box_geometry",
    "check_winding",
    "checker_cutout_png",
    "combine_geometry",
    "cylinder_geometry",
    "subdivided_box_geometry",
    "look_at_quat",
    "mesh_from_triangles",
    "normalise",
    "quad_geometry",
    "spiky_sphere_geometry",
    "write_rgba_png",
    "quat_axis_angle",
    "quat_conjugate",
    "quat_from_to",
    "quat_multiply",
    "rotate_by_quat",
    "sphere_geometry",
    "tetrahedron_geometry",
    "vec_cross",
    "vec_sub",
    "write_gltf",
]
