"""Minimal, byte-deterministic RGBA PNG writer.

Generated assets embed their textures as data URIs, and the committed `.gltf` are
regenerated by the build — so the encoder's output has to be identical everywhere, not
merely valid. That rules out `zlib.compress`: its output is a function of the zlib build,
so the same source could produce a different `.gltf` on another machine. Instead the
image data goes into DEFLATE **stored** (uncompressed) blocks, whose layout is fully
specified by RFC 1951, with the zlib wrapper and Adler-32 written by hand. The files are
small (the alpha-mask texture is a few KiB), so the size cost is irrelevant next to
reproducibility.

Only what the generators need: 8-bit RGBA, no interlacing, no ancillary chunks.
"""

import struct
import zlib

_PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
# RFC 1951 caps a stored block's payload at 65535 bytes.
_MAX_STORED_BLOCK = 0xFFFF


def _chunk(tag, payload):
    return (struct.pack(">I", len(payload)) + tag + payload
            + struct.pack(">I", zlib.crc32(tag + payload) & 0xFFFFFFFF))


def _deflate_stored(data):
    """Zlib stream carrying `data` in stored blocks — no compression, no encoder choices."""
    out = bytearray(b"\x78\x01")  # CMF/FLG: deflate, 32K window, no dictionary, fastest
    if not data:
        out += b"\x01\x00\x00\xff\xff"
    for start in range(0, len(data), _MAX_STORED_BLOCK):
        block = data[start:start + _MAX_STORED_BLOCK]
        final = 1 if start + _MAX_STORED_BLOCK >= len(data) else 0
        out += struct.pack("<BHH", final, len(block), len(block) ^ 0xFFFF)
        out += block
    out += struct.pack(">I", zlib.adler32(bytes(data)) & 0xFFFFFFFF)
    return bytes(out)


def write_rgba_png(width, height, pixels):
    """PNG bytes for an 8-bit RGBA image.

    `pixels` is a row-major sequence of `(r, g, b, a)` tuples, `width * height` long."""
    if len(pixels) != width * height:
        raise ValueError(f"expected {width * height} pixels, got {len(pixels)}")
    raw = bytearray()
    for y in range(height):
        raw.append(0)  # per-row filter type 0 (None) — keeps the bytes trivially predictable
        for x in range(width):
            r, g, b, a = pixels[y * width + x]
            raw += bytes((r & 0xFF, g & 0xFF, b & 0xFF, a & 0xFF))
    # Colour type 6 = truecolour with alpha; bit depth 8; no interlace.
    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    return (_PNG_SIGNATURE + _chunk(b"IHDR", header)
            + _chunk(b"IDAT", _deflate_stored(bytes(raw))) + _chunk(b"IEND", b""))


def checker_cutout_png(size=64, squares=8, opaque=(230, 220, 90, 255), hole=(0, 0, 0, 0)):
    """A checkerboard whose dark squares are fully TRANSPARENT — an alpha-mask texture
    with real holes, so a MASK material actually discards fragments (and a shadow pass
    that ignores the mask casts a visibly solid, wrong silhouette)."""
    step = max(1, size // squares)
    pixels = []
    for y in range(size):
        for x in range(size):
            pixels.append(opaque if ((x // step) + (y // step)) % 2 == 0 else hole)
    return write_rgba_png(size, size, pixels)
